inherit_gem:
  bixby: bixby_default.yml

AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - 'db/**/*'
    - 'script/**/*'
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'config/initializers/explain_partials.rb'

# BEGIN; Disabled in move to 2.3 sytax linter
Style/FrozenStringLiteralComment:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/SafeNavigation:
  Enabled: false
# END; Disabled in move to 2.3 sytax linter

Layout/SpaceAroundOperators:
  Exclude:
    - 'spec/fixtures/form_submission_params/*'

Layout/SpaceInsideHashLiteralBraces:
    Exclude:
      - 'spec/fixtures/form_submission_params/*'

Layout/MultilineHashBraceLayout:
  Exclude:
    - 'spec/controllers/hyrax/etds_controller_spec.rb'

Lint/Void:
  Enabled: false

Lint/UnusedBlockArgument:
  Enabled: false

Lint/AmbiguousOperator:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/LineLength:
  Exclude:
    - 'spec/fixtures/form_submission_params/*'
    - 'spec/services/hyrax/workflow/pending_approval_notification_spec.rb'
    - 'spec/features/rollins_workflow_etd_spec.rb'
    - 'app/inputs/fields_without_blank.rb'

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Rails/FindBy:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false
  
RSpec/MessageSpies:
  Exclude:
    - 'spec/controllers/hyrax/admin/workflows_controller_spec.rb'

RSpec/MultipleExpectations:
  Enabled: false

Style/CommentAnnotation:
  Enabled: false

# complaining about the Capfile name. Wants it to be snake_case - re-enabling, should be fixed by updated Bixby
Style/FileName:
  Enabled: true

Style/Semicolon:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  Enabled: false

Layout/AlignParameters:
  Exclude:
    - 'app/models/etd.rb'
    - 'spec/controllers/hyrax/etds_controller_spec.rb'

Layout/ClosingParenthesisIndentation:
  Enabled: false

RSpec/InstanceVariable:
  Enabled: false

RSpec/DescribeClass:
  Exclude:
    - 'spec/javascripts/jasmine_spec.rb'

RSpec/NestedGroups:
  Enabled: false

RSpec/VerifiedDoubles:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false
