inherit_from: .rubocop_todo.yml

inherit_gem:
  bixby: bixby_default.yml

AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - 'db/**/*'
    - 'script/**/*'
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'config/initializers/explain_partials.rb'
    - 'node_modules/**/*'
    - lib/tasks/laney_csv_report.rake

# BEGIN; Disabled in move to 2.3 sytax linter
Style/FrozenStringLiteralComment:
  Enabled: false

Style/GuardClause:
  Exclude:
    - 'app/controllers/hyrax/etds_controller.rb'

Style/NumericPredicate:
  Enabled: false

Style/SafeNavigation:
  Enabled: false
# END; Disabled in move to 2.3 sytax linter

Style/SymbolProc:
  Enabled: false

Layout/HashAlignment:
  Enabled: false

Layout/SpaceAroundOperators:
  Exclude:
    - 'spec/fixtures/form_submission_params/*'

Layout/SpaceInsideHashLiteralBraces:
    Exclude:
      - 'spec/fixtures/form_submission_params/*'

Layout/MultilineHashBraceLayout:
  Exclude:
    - 'spec/controllers/hyrax/etds_controller_spec.rb'

Layout/FirstHashElementIndentation:
  Exclude:
    - 'spec/models/in_progress_etd_spec.rb'

Lint/Void:
  Enabled: false

Lint/UnusedBlockArgument:
  Enabled: false

Lint/AmbiguousOperator:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Layout/LineLength:
  Exclude:
    - 'spec/fixtures/form_submission_params/*'
    - 'spec/services/hyrax/workflow/pending_approval_notification_spec.rb'
    - 'spec/features/rollins_workflow_etd_spec.rb'
    - 'app/inputs/fields_without_blank.rb'
    - 'spec/factories/solr_document.rb'
    - 'spec/presenters/etd_file_set_presenter_spec.rb'

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Rails/Delegate:
  Exclude:
    - 'app/models/schools/department.rb'
    - 'app/models/schools/subfield.rb'

Rails/FindBy:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/MessageSpies:
  Exclude:
    - 'spec/controllers/hyrax/admin/workflows_controller_spec.rb'
    - 'spec/actors/primary_file_title_actor_spec.rb'
    - 'spec/controllers/hyrax/etds_controller_spec.rb'

RSpec/MultipleExpectations:
  Enabled: false

RSpec/NotToNot:
  Exclude:
    - 'spec/models/ability_spec.rb'

Style/CommentAnnotation:
  Enabled: false

Style/Semicolon:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  Enabled: false

Layout/ParameterAlignment:
  Exclude:
    - 'app/models/etd.rb'
    - 'spec/controllers/hyrax/etds_controller_spec.rb'

Layout/ClosingParenthesisIndentation:
  Enabled: false

RSpec/InstanceVariable:
  Enabled: false

RSpec/DescribeClass:
  Exclude:
    - 'spec/javascripts/jasmine_spec.rb'

RSpec/LetSetup:
  Exclude:
    - "spec/models/schools/*.rb"

RSpec/NestedGroups:
  Enabled: false

RSpec/VerifiedDoubles:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

RSpec/AnyInstance:
  Exclude:
    - 'spec/system/check_school_spec.rb'
