terms:
    - id: Biochemistry, Cell & Developmental Biology
      term: Biochemistry, Cell & Developmental Biology
    - id: Cancer Biology
      term: Cancer Biology
    - id: Genetics and Molecular Biology
      term: Genetics and Molecular Biology
    - id: Immunology
      term: Immunology
    - id: Microbiology & Molecular Genetics
      term: Microbiology & Molecular Genetics
    - id: Molecular & Systems Pharmacology
      term: Molecular & Systems Pharmacology
    - id: Neuroscience
      term: Neuroscience
    - id: Nutrition and Health Sciences
      term: Nutrition and Health Sciences
    - id: Population Biology, Ecology & Evolution
      term: Population Biology, Ecology & Evolution
