terms:
    - id: 'ThD'
      term: 'ThD'
    - id: 'PhD'
      term: 'PhD'
    - id: 'DNP'
      term: 'DNP'
    - id: 'MA'
      term: 'MA'
    - id: 'MS'
      term: 'MS'
    - id: 'MDiv'
      term: 'MDiv'
    - id: 'MTS'
      term: 'MTS'
    - id: 'MPH'
      term: 'MPH'
    - id: 'MSPH'
      term: 'MSPH'
    - id: 'BA'
      term: 'BA'
    - id: 'BS'
      term: 'BS'
    - id: 'BBA'
      term: 'BBA'
