terms:
    - id: 'Th.D.'
      term: 'Th.D.'
    - id: 'Ph.D.'
      term: 'PhD'
    - id: 'DMin'
      term: 'DMin'
    - id: 'D.N.P.'
      term: 'DNP'
    - id: 'M.A.'
      term: 'MA'
    - id: 'M.S.'
      term: 'MS'
    - id: 'M.Div.'
      term: 'MDiv'
    - id: 'M.T.S.'
      term: 'MTS'
    - id: 'M.P.H.'
      term: 'MPH'
    - id: 'M.S.P.H.'
      term: 'MSPH'
    - id: 'B.A.'
      term: 'BA'
    - id: 'B.S.'
      term: 'BS'
    - id: 'B.B.A.'
      term: 'BBA'
    - id: 'ThD'
      term: 'Th.D.'
      active: false
    - id: 'PhD'
      term: 'PhD'
      active: false
    - id: 'DNP'
      term: 'DNP'
      active: false
    - id: 'MA'
      term: 'MA'
      active: false
    - id: 'MS'
      term: 'MS'
      active: false
    - id: 'MDiv'
      term: 'MDiv'
      active: false
    - id: 'MTS'
      term: 'MTS'
      active: false
    - id: 'MPH'
      term: 'MPH'
      active: false
    - id: 'MSPH'
      term: 'MSPH'
      active: false
    - id: 'BA'
      term: 'BA'
      active: false
    - id: 'BS'
      term: 'BS'
      active: false
    - id: 'BBA'
      term: 'BBA'
      active: false
