terms:
    - id: Clinical Psychology
      term: Clinical Psychology
    - id: Cognitive and Developmental Psychology
      term: Cognitive and Developmental Psychology
    - id: Neuroscience and Animal Behavior
      term: Neuroscience and Animal Behavior