terms:
    - id: Behavioral and Systems Neuroscience
      term: Behavioral and Systems Neuroscience
    - id: Clinical Psychology
      term: Clinical Psychology
    - id: Clinical Science
      term: Clinical Science
    - id: Cognition and Development
      term: Cognition and Development
    - id: Cognitive and Computational Science
      term: Cognitive and Computational Science
    - id: Developmental Science
      term: Developmental Science
    - id: Neuroscience and Animal Behavior
      term: Neuroscience and Animal Behavior
