terms:
    - id: Comparative Literature and Religion
      term: Comparative Literature and Religion
    - id: Ethics and Society
      term: Ethics and Society
    - id: Hebrew Bible
      term: Hebrew Bible
    - id: Historical Studies in Theology and Religion
      term: Historical Studies in Theology and Religion
    - id: New Testament
      term: New Testament
    - id: Person, Community and Religious Practices
      term: Person, Community and Religious Practices
    - id: Theological Studies
      term: Theological Studies
    - id: West and South Asian Religions
      term: West and South Asian Religions
