terms:
    - id: 'Candler School of Theology'
      term: 'Candler School of Theology'
      programs: 'candler_programs'
    - id: 'Emory College'
      term: 'Emory College'
      programs: 'emory_programs'
    - id: 'Laney Graduate School'
      term: 'Laney Graduate School'
      programs: 'laney_programs'
    - id: 'Nell Hodgson Woodruff School of Nursing'
      term: 'Nell Hodgson Woodruff School of Nursing'
      programs: 'woodruff_programs'
    - id: 'Rollins School of Public Health'
      term: 'Rollins School of Public Health'
      programs: 'rollins_programs'
