terms:
    - id: 'Adult-Gerontology: Acute Care NP'
      term: 'Adult-Gerontology: Acute Care NP'
    - id: 'Adult-Gerontology: Primary Care NP'
      term: 'Adult-Gerontology: Primary Care NP'
    - id: 'Certified Registered Nurse Anesthetist'
      term: 'Certified Registered Nurse Anesthetist'
    - id: 'Family/Emergency NP'
      term: 'Family/Emergency NP'
    - id: 'Family NP'
      term: 'Family NP'
    - id: 'Pediatric Acute Care NP'
      term: 'Pediatric Acute Care NP'
    - id: 'Pediatric Primary Care NP'
      term: 'Pediatric Primary Care NP'
    - id: 'Psychiatric Mental Health NP'
      term: 'Psychiatric Mental Health NP'
    - id: 'Women’s Health/Gender Related NP'
      term: 'Women’s Health/Gender Related NP'
    - id: 'Master of Science in Nursing to Doctor of Nursing Practice'
      term: 'Master of Science in Nursing to Doctor of Nursing Practice'
