terms:
    - id:   'Adult-Gerontology: Acute Care Nursing Practice'
      term: 'Adult-Gerontology: Acute Care Nursing Practice'
    - id:   'Adult-Gerontology: Primary Care Nursing Practice'
      term: 'Adult-Gerontology: Primary Care Nursing Practice'
    - id:   'Certified Registered Nurse Anesthetist'
      term: 'Certified Registered Nurse Anesthetist'
    - id:   'Family/Emergency Nursing Practice'
      term: 'Family/Emergency Nursing Practice'
    - id:   'Family Nursing Practice'
      term: 'Family Nursing Practice'
    - id:   'Pediatric Acute Care Nursing Practice'
      term: 'Pediatric Acute Care Nursing Practice'
    - id:   'Pediatric Primary Care Nursing Practice'
      term: 'Pediatric Primary Care Nursing Practice'
    - id:   'Psychiatric Mental Health Nursing Practice'
      term: 'Psychiatric Mental Health Nursing Practice'
    - id:   'Women’s Health/Gender Related Nursing Practice'
      term: 'Women’s Health/Gender Related Nursing Practice'
    - id:   'Master of Science in Nursing to Doctor of Nursing Practice'
      term: 'Master of Science in Nursing to Doctor of Nursing Practice'
