---
static:
  citation_dissertation_institution: Emory University
attributes:
  citation_title: title
  citation_author: creator
  citation_date: degree_awarded
  citation_type: submitting_type
  dc.type: submitting_type
  citation_keywords: research_field
  citation_pdf_url: download_url
